### ISSUE TITLE
String normalization

### ISSUE THREAD

**Issue by Haroenv** [kuroljov/triematch#13]
When implementing a search, you would usually normalise the sting, since human people will search for something in lowercase, rather than the casing it was stored in. You could do this now by making your own normalisation and passing it both to the keys when setting, as well as to the match string before sending, but I was wondering how you solve this yourself

**Comment by viktor-ku** [comment]
@Haroenv Hi! Thank you for writing an issue! 

I am normalizing it prior to insertion into the structure when needed (and I don't need to do it all the time, think phone numbers). I actually thought about adding normalization, but I don't want to slow things down when you don't maybe need it.

Feel free to leave your proposal thought.

**Comment by Haroenv** [comment]
That makes sense to leave it out of the library, when trying it out I had good first results with just calling `toLocaleLowercase`, but that doesn't deal with accents etc. Maybe something using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator could be an option. 

Anyway, since you agree it shouldn't be part of the default implementation, let's close this
